name: Suggest a new recommendation
description: Add a new recommendation to the list
title: "Suggest a new recommendation"
labels: ["new"]
assignees:
  - billiem
body:
  - type: input
    id: name
    attributes:
      label: Name
      description: Name of the recommendation
    validations:
      required: true
  - type: dropdown
    id: section
    attributes:
      label: Section
      description: Section of the recommendation
      options:
        - Hair
        - Piercings
        - Lashes
        - Tattoos
        - Makeup
        - Beautician
        - Electrolysis
        - Nails
        - Clothes
        - Underwear
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: url
      description: Link to the recommendation (social media/ website)
    validations:
      required: true
  - type: input
    id: Location
    attributes:
      label: Location
      description: Location of the recommendation (e.g. City Centre, Online)
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: info
      description: Further information about the recommendation
    validations:
      required: false