name: 'workflow'
on:
  issues:
    types: [opened]

jobs:
  create-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Parse Issue Body
        uses: zentered/issue-forms-body-parser@main
        id: parse

      - run: echo ${{toJSON(steps.parse.outputs.data)}}
      - run: echo ${{toJSON(steps.parse.outputs.data.name)}}
      - run: echo ${{toJSON(steps.parse.outputs.data.name.text)}}
      - run: echo ${{toJSON(steps.parse.outputs.data.name.info)}}
      - run: echo ${{toJSON(steps.parse.outputs.data.name.info.title)}}

      - name: Add issue data to yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: '_data/links.yml'
          propertyPath: ''
          branch: master
          targetBranch: master
          createPR: true
          message: 'Created PR for new link: ${{ steps.parse.outputs.data.name }}' 
          changes: |
            {
              ${{ steps.parse.outputs.data.section.text }}.${{ steps.parse.outputs.data.name.text }}.info: ${{ steps.parse.outputs.data.info.text }}
            }